version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: npm ci
      - run: npm test
workflows:
  version: 2
  test-and-building:
    jobs:
      - test:
        filters:
          branches:
            only:
              - main
              - /feature\/.*/
              - /fix\/.*/
  