version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  deploy:
    docker: 
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: "s3://abazlinton-react-persons-app/"
          arguments: |
            --cache-control "max-age=86400"
workflows:
  version: 2
  test-and-build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
                - /fix\/.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
  